# Generated by Django 5.0 on 2024-03-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0007_alter_collectionrequest_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='area',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='area',
            field=models.ManyToManyField(to='my_work.area'),
        ),
    ]
