# Generated by Django 5.0 on 2024-03-19 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0008_remove_userlocation_area_userlocation_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='area',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='user',
        ),
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('buildingno', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_work.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CollectionMessege',
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
