# Generated by Django 4.2.6 on 2024-03-21 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0009_remove_userlocation_area_remove_userlocation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
