# Generated by Django 5.0 on 2024-03-22 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0013_alter_usergarbagebin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userarea', to=settings.AUTH_USER_MODEL),
        ),
    ]
