# Generated by Django 5.0 on 2024-03-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0015_complaint_accepted_complaint_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
