# Generated by Django 5.0 on 2024-03-26 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0016_remove_collectionrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
