# Generated by Django 5.0 on 2024-03-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0017_alter_collectionrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='created_at',
            field=models.DateField(),
        ),
    ]
