# Generated by Django 5.0 on 2024-03-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0018_alter_collectionrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
    ]
