# Generated by Django 5.0 on 2024-04-01 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0020_delete_usergarbagebin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGarbageBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('bin', models.ManyToManyField(to='my_work.garbagebin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garbage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
