# Generated by Django 5.0 on 2024-04-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0022_remove_usergarbagebin_bin_usergarbagebin_bin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserArea',
        ),
    ]
