# Generated by Django 5.0 on 2024-04-03 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0024_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='public',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public', to=settings.AUTH_USER_MODEL),
        ),
    ]
