# Generated by Django 5.0 on 2024-04-04 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0025_collectionrequest_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionrequest',
            name='public',
        ),
        migrations.RemoveField(
            model_name='collectionrequest',
            name='rejected',
        ),
        migrations.CreateModel(
            name='RequestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('result', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='R_name', to='my_work.collectionrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='R_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
