# Generated by Django 5.0 on 2024-04-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0027_alter_requesttable_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='R_name', to='my_work.collectionrequest'),
        ),
    ]
