# Generated by Django 4.1.5 on 2024-04-17 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0031_alter_requesttable_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
