# Generated by Django 4.1.5 on 2024-04-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0032_paymentscanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentscanner',
            name='scanner',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
