# Generated by Django 4.1.5 on 2024-04-17 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0033_alter_paymentscanner_scanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentscanner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scanner', to=settings.AUTH_USER_MODEL),
        ),
    ]
