# Generated by Django 4.1.5 on 2024-04-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0034_alter_paymentscanner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentscanner',
            name='user',
        ),
    ]
