# Generated by Django 4.1.5 on 2024-04-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0035_remove_paymentscanner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentscanner',
            name='scanner',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
