# Generated by Django 4.1.5 on 2024-04-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0036_alter_paymentscanner_scanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentScanner',
        ),
    ]
